### ISSUE TITLE
Firewall_force mode

### ISSUE THREAD

**Issue by DI555** [EasyLazyBean/Fiwalld#1]
foa, thank you for the great app!

please, provide firewall_force mode, when DNS services not yet connected, but firewall(and local vpn with it) is functioning after switch-on button(unprotected/protected button). it may take to add new button near, like "dns connect" or smth to connect/reconnect dns services.
 it is a very useful feature, providing firewall defendness more stable and better.
many thanks in anvance!

**Comment by EasyLazyBean** [comment]
Hi, when you change DNS settings, there is already a reconnect button displayed. I may not understand you well about "firewall_force" mode.

**Comment by DI555** [comment]
i mean, FD doesn’t want switch on firewall untill dns services be connected (
so it’s impossible to be it switch on without internet connection(

firewall_force mode should let be firewall started without internet connection (without dns services yet started)
and "dns connect" button will start or restart dns services after 👍

**Comment by EasyLazyBean** [comment]
Hi, I got your point, thanks for the suggestion. Unable to start fiwalld with "DNS failed" to alert users that they may have connectivity issues, this is the current design. I will think about whether it is necessary to modify the current design and keep this issue open.

**Comment by EasyLazyBean** [comment]
Hi, DI555. Your suggestion is accepted. Related improment is added in V2.1.2. Thanks!

**Comment by DI555** [comment]
great, it’s exactly what i ment 👍
